<?php

namespace App\Http\Controllers\Employee;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Inertia\Inertia;
use Carbon\Carbon;

class SalaryController extends Controller
{
    public function index()
    {
        $user = Auth::user();

        // Get department name from departments table
        $department = null;
        if ($user->department_id) {
            $dept = DB::table('departments')->where('id', $user->department_id)->first();
            $department = $dept ? $dept->name : 'Not Assigned';
        } else {
            $department = $user->department ?? 'Not Assigned';
        }

        $grossSalary = floatval($user->salary ?? 0);

        // Get current month's data
        $currentMonth = Carbon::now()->format('F Y'); // e.g., "February 2026"

        /* ---------------- CHECK IF PAYROLL HAS BEEN GENERATED BY HR ---------------- */

        $payroll = DB::table('payrolls')
            ->where('employee_id', $user->employee_id)
            ->where('month', $currentMonth)
            ->first();

        if ($payroll) {
            // HR has generated payroll - fetch attendance data for breakdown
            $currentMonthNum = Carbon::now()->month;
            $currentYear = Carbon::now()->year;
            $workingDaysInMonth = 22;

            // Get attendance records
            $allAttendanceRecords = DB::table('attendances')
                ->where('employee_id', $user->employee_id)
                ->whereMonth('date', $currentMonthNum)
                ->whereYear('date', $currentYear)
                ->get();

            // Calculate attendance stats
            $markedAbsences = $allAttendanceRecords->where('status', 'absent')->count();
            $daysWithRecords = $allAttendanceRecords->count();
            $daysWithoutRecords = max(0, $workingDaysInMonth - $daysWithRecords);
            $totalAbsences = $markedAbsences + $daysWithoutRecords;

            $workingRecords = $allAttendanceRecords->where('status', '!=', 'absent');
            $lateCount = 0;
            $totalLateMinutes = 0;
            $totalHoursWorked = 0;
            $undertimeHours = 0;
            $presentDays = 0;

            foreach ($workingRecords as $record) {
                if (!$record->check_in || !$record->check_out) {
                    continue;
                }

                $presentDays++;

                // Use stored late_minutes from database (calculated by HR)
                if ($record->late_minutes > 0) {
                    $lateCount++;
                    $totalLateMinutes += $record->late_minutes;
                }

                // Use stored hours_worked from database (calculated by HR)
                $hoursWorked = floatval($record->hours_worked ?? 0);
                $totalHoursWorked += $hoursWorked;
                
                // Calculate undertime from stored hours
                if ($hoursWorked < 8.0) {
                    $undertimeHours += (8.0 - $hoursWorked);
                }
            }

            // Calculate individual deductions for display
            $dailyRate = $payroll->basic_salary / $workingDaysInMonth;
            $hourlyRate = $dailyRate / 8;

            $absenceDeduction = round($dailyRate * $totalAbsences, 2);
            $lateDeduction = round(($totalLateMinutes / 60) * $hourlyRate, 2);
            $undertimeDeduction = round($undertimeHours * $hourlyRate, 2);
            $totalDeductions = $absenceDeduction + $lateDeduction + $undertimeDeduction;

            return Inertia::render('Employee/Salary/Index', [
                'employee' => [
                    'id' => $user->id,
                    'employee_id' => $user->employee_id ?? $user->id,
                    'name' => $user->name,
                    'department' => $department,
                ],
                'salary' => [
                    'full_salary' => $payroll->basic_salary,
                    'deductions' => $payroll->deductions,
                ],
                'attendance' => [
                    'absences' => $totalAbsences,
                    'late_count' => $lateCount,
                    'total_late_minutes' => round($totalLateMinutes, 0),
                    'total_hours_worked' => round($totalHoursWorked, 2),
                    'expected_hours' => 176,
                    'undertime_hours' => round($undertimeHours, 2),
                    'present_days' => $presentDays,
                    'total_working_days' => $workingDaysInMonth,
                ],
                'deductions' => [
                    'absence_deduction' => $absenceDeduction,
                    'late_deduction' => $lateDeduction,
                    'undertime_deduction' => $undertimeDeduction,
                    'total_deductions' => $totalDeductions,
                ],
                'netSalary' => $payroll->basic_salary - $totalDeductions,
                'payrollGenerated' => true,
            ]);
        }

        /* ---------------- NO PAYROLL GENERATED - SHOW MESSAGE ---------------- */

        return Inertia::render('Employee/Salary/Index', [
            'employee' => [
                'id' => $user->id,
                'employee_id' => $user->employee_id ?? $user->id,
                'name' => $user->name,
                'department' => $department,
            ],
            'salary' => [
                'full_salary' => $grossSalary,
                'deductions' => 0,
            ],
            'attendance' => [
                'absences' => 0,
                'late_count' => 0,
                'total_late_minutes' => 0,
                'total_hours_worked' => 0,
                'expected_hours' => 176,
                'undertime_hours' => 0,
                'present_days' => 0,
                'total_working_days' => 22,
            ],
            'deductions' => [
                'absence_deduction' => 0,
                'late_deduction' => 0,
                'undertime_deduction' => 0,
                'total_deductions' => 0,
            ],
            'netSalary' => $grossSalary,
            'payrollGenerated' => false,
        ]);
    }
}