<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 24px;
            border-bottom: 2px solid #dc2626;
            padding-bottom: 16px;
        }

        .header h1 {
            font-size: 22px;
            font-weight: bold;
            color: #dc2626;
        }

        .header p {
            font-size: 12px;
            color: #666;
            margin-top: 4px;
        }

        .meta {
            display: flex;
            justify-content: space-between;
            margin-bottom: 16px;
            font-size: 11px;
            color: #555;
        }

        .filters {
            background: #f3f4f6;
            padding: 8px 12px;
            border-radius: 4px;
            margin-bottom: 16px;
            font-size: 11px;
        }

        .filters span {
            margin-right: 16px;
        }

        .summary {
            width: 100%;
            margin-bottom: 20px;
        }

        .summary td {
            width: 25%;
            padding: 10px;
            border-radius: 6px;
            text-align: center;
        }

        .summary td.present {
            background: #dcfce7;
            border: 1px solid #16a34a;
        }

        .summary td.absent {
            background: #fee2e2;
            border: 1px solid #dc2626;
        }

        .summary td.late {
            background: #fef9c3;
            border: 1px solid #ca8a04;
        }

        .summary td.total {
            background: #dbeafe;
            border: 1px solid #2563eb;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        thead tr {
            background: #dc2626;
            color: white;
        }

        thead th {
            padding: 8px 10px;
            text-align: left;
            font-size: 11px;
            font-weight: bold;
        }

        tbody tr:nth-child(even) {
            background: #f9fafb;
        }

        tbody tr:nth-child(odd) {
            background: #ffffff;
        }

        tbody td {
            padding: 7px 10px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 11px;
        }

        .status-present {
            color: #16a34a;
            font-weight: bold;
        }

        .status-absent {
            color: #dc2626;
            font-weight: bold;
        }

        .status-late {
            color: #ca8a04;
            font-weight: bold;
        }

        .status-on_leave {
            color: #2563eb;
            font-weight: bold;
        }

        .footer {
            margin-top: 24px;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #e5e7eb;
            padding-top: 12px;
        }
    </style>
</head>

<body>

    <div class="header">
        <h1>Employee Management System</h1>
        <p>Attendance Report</p>
    </div>

    <div class="meta">
        <span>Generated by: {{ $generatedBy }}</span>
        <span>Generated at: {{ $generatedAt }}</span>
    </div>

    <div class="filters">
        @if($dateFrom || $dateTo)
            <span><strong>Date Range:</strong> {{ $dateFrom ?? 'Start' }} — {{ $dateTo ?? 'End' }}</span>
        @endif
        @if($employeeName)
            <span><strong>Employee:</strong> {{ $employeeName }}</span>
        @endif
        @if($statusFilter)
            <span><strong>Status:</strong> {{ ucfirst($statusFilter) }}</span>
        @endif
    </div>

    <table class="summary">
        <tr>
            <td class="total">
                <div class="number">{{ $totalRecords }}</div>
                <div class="label">Total Records</div>
            </td>
            <td class="present">
                <div class="number">{{ $totalPresent }}</div>
                <div class="label">Present</div>
            </td>
            <td class="late">
                <div class="number">{{ $totalLate }}</div>
                <div class="label">Late</div>
            </td>
            <td class="absent">
                <div class="number">{{ $totalAbsent }}</div>
                <div class="label">Absent</div>
            </td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Employee</th>
                <th>Department</th>
                <th>Date</th>
                <th>Check In</th>
                <th>Check Out</th>
                <th>Hours</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($records as $index => $record)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $record->employee_name }}</td>
                    <td>{{ $record->department ?? 'N/A' }}</td>
                    <td>{{ \Carbon\Carbon::parse($record->date)->format('M d, Y') }}</td>
                    <td>{{ $record->check_in ? \Carbon\Carbon::parse($record->check_in)->format('h:i A') : '--' }}</td>
                    <td>{{ $record->check_out ? \Carbon\Carbon::parse($record->check_out)->format('h:i A') : '--' }}</td>
                    <td>{{ $record->hours_worked ?? 0 }} hrs</td>
                    <td class="status-{{ $record->status }}">{{ ucfirst(str_replace('_', ' ', $record->status)) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align: center; padding: 20px; color: #999;">No attendance records found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Employee Management System &mdash; Attendance Report &mdash; {{ $generatedAt }}</p>
    </div>

</body>

</html>