<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee List Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }

        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #dc2626; padding-bottom: 14px; }
        .header h1 { font-size: 22px; font-weight: bold; color: #dc2626; }
        .header p { font-size: 12px; color: #666; margin-top: 4px; }

        .meta { width: 100%; margin-bottom: 14px; font-size: 11px; color: #555; }
        .meta td { width: 50%; }
        .meta td:last-child { text-align: right; }

        .summary { width: 100%; border-collapse: separate; border-spacing: 8px; margin-bottom: 20px; }
        .summary td { width: 33%; padding: 10px; border-radius: 6px; text-align: center; }
        .summary td.total      { background: #dbeafe; border: 1px solid #2563eb; }
        .summary td.employees  { background: #dcfce7; border: 1px solid #16a34a; }
        .summary td.hr         { background: #f3e8ff; border: 1px solid #7c3aed; }
        .number { font-size: 18px; font-weight: bold; }
        .label  { font-size: 10px; color: #555; margin-top: 2px; }

        table.main { width: 100%; border-collapse: collapse; }
        table.main thead tr { background: #dc2626; color: white; }
        table.main thead th { padding: 8px 10px; text-align: left; font-size: 11px; font-weight: bold; }
        table.main tbody tr:nth-child(even) { background: #f9fafb; }
        table.main tbody tr:nth-child(odd)  { background: #ffffff; }
        table.main tbody td { padding: 7px 10px; border-bottom: 1px solid #e5e7eb; font-size: 11px; }

        .role-employee { color: #16a34a; font-weight: bold; }
        .role-hr       { color: #7c3aed; font-weight: bold; }
        .role-admin    { color: #dc2626; font-weight: bold; }

        .footer { margin-top: 24px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #e5e7eb; padding-top: 12px; }
    </style>
</head>
<body>

    <div class="header">
        <h1>Employee Management System</h1>
        <p>Employee List Report</p>
    </div>

    <table class="meta">
        <tr>
            <td>Generated by: {{ $generatedBy }}</td>
            <td style="text-align:right;">Generated at: {{ $generatedAt }}</td>
        </tr>
    </table>

    <!-- Summary Cards -->
    <table class="summary">
        <tr>
            <td class="total">
                <div class="number">{{ $totalEmployees }}</div>
                <div class="label">Total Employees</div>
            </td>
            <td class="employees">
                <div class="number">{{ $totalRegular }}</div>
                <div class="label">Regular Employees</div>
            </td>
            <td class="hr">
                <div class="number">{{ $totalHR }}</div>
                <div class="label">HR Staff</div>
            </td>
        </tr>
    </table>

    <!-- Employee Table -->
    <table class="main">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Department</th>
                <th>Role</th>
                <th>Hire Date</th>
                <th>Salary</th>
            </tr>
        </thead>
        <tbody>
            @forelse($employees as $index => $employee)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $employee->name }}</td>
                <td>{{ $employee->email }}</td>
                <td>{{ $employee->department ?? 'N/A' }}</td>
                <td class="role-{{ $employee->role }}">{{ ucfirst($employee->role) }}</td>
                <td>{{ $employee->hire_date ? \Carbon\Carbon::parse($employee->hire_date)->format('M d, Y') : 'N/A' }}</td>
                <td>&#8369;{{ number_format($employee->salary ?? 0, 2) }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="text-align:center; padding:20px; color:#999;">
                    No employees found
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Employee Management System &mdash; Employee List Report &mdash; {{ $generatedAt }}</p>
    </div>

</body>
</html>