<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Payroll Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 14px;
        }

        .header h1 {
            font-size: 22px;
            font-weight: bold;
            color: #2563eb;
        }

        .header p {
            font-size: 12px;
            color: #666;
            margin-top: 4px;
        }

        .meta {
            width: 100%;
            margin-bottom: 14px;
            font-size: 11px;
            color: #555;
        }

        .meta td {
            width: 50%;
        }

        .meta td:last-child {
            text-align: right;
        }

        .month-label {
            text-align: center;
            font-size: 14px;
            font-weight: bold;
            color: #1e40af;
            margin-bottom: 16px;
        }

        .summary {
            width: 100%;
            border-collapse: separate;
            border-spacing: 8px;
            margin-bottom: 20px;
        }

        .summary td {
            width: 25%;
            padding: 10px;
            border-radius: 6px;
            text-align: center;
        }

        .summary td.employees {
            background: #dbeafe;
            border: 1px solid #2563eb;
        }

        .summary td.gross {
            background: #dcfce7;
            border: 1px solid #16a34a;
        }

        .summary td.deduct {
            background: #fee2e2;
            border: 1px solid #dc2626;
        }

        .summary td.net {
            background: #f3e8ff;
            border: 1px solid #7c3aed;
        }

        .number {
            font-size: 18px;
            font-weight: bold;
        }

        .label {
            font-size: 10px;
            color: #555;
            margin-top: 2px;
        }

        table.main {
            width: 100%;
            border-collapse: collapse;
        }

        table.main thead tr {
            background: #2563eb;
            color: white;
        }

        table.main thead th {
            padding: 8px 10px;
            text-align: left;
            font-size: 11px;
            font-weight: bold;
        }

        table.main tbody tr:nth-child(even) {
            background: #f9fafb;
        }

        table.main tbody tr:nth-child(odd) {
            background: #ffffff;
        }

        table.main tbody td {
            padding: 7px 10px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 11px;
        }

        table.main tfoot tr {
            background: #1e40af;
            color: white;
            font-weight: bold;
        }

        table.main tfoot td {
            padding: 8px 10px;
            font-size: 11px;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .text-green {
            color: #16a34a;
            font-weight: bold;
        }

        .text-red {
            color: #dc2626;
            font-weight: bold;
        }

        .footer {
            margin-top: 24px;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #e5e7eb;
            padding-top: 12px;
        }
    </style>
</head>

<body>

    <div class="header">
        <h1>Employee Management System</h1>
        <p>Payroll Report</p>
    </div>

    <table class="meta">
        <tr>
            <td>Generated by: {{ $generatedBy }}</td>
            <td style="text-align:right;">Generated at: {{ $generatedAt }}</td>
        </tr>
    </table>

    <div class="month-label">Payroll Period: {{ $month }}</div>

    <!-- Summary Cards -->
    <table class="summary">
        <tr>
            <td class="employees">
                <div class="number">{{ $totalEmployees }}</div>
                <div class="label">Total Employees</div>
            </td>
            <td class="gross">
                <div class="number">&#8369;{{ number_format($totalGross, 2) }}</div>
                <div class="label">Total Gross</div>
            </td>
            <td class="deduct">
                <div class="number">&#8369;{{ number_format($totalDeductions, 2) }}</div>
                <div class="label">Total Deductions</div>
            </td>
            <td class="net">
                <div class="number">&#8369;{{ number_format($totalNet, 2) }}</div>
                <div class="label">Total Net Pay</div>
            </td>
        </tr>
    </table>

    <!-- Payroll Table -->
    <table class="main">
        <thead>
            <tr>
                <th>Serial No</th>
                <th>Employee</th>
                <th>Department</th>
                <th class="text-right">Gross Salary</th>
                <th class="text-right">Deductions</th>
                <th class="text-right">Net Salary</th>
                <th class="text-center">Absences</th>
                <th class="text-center">Late</th>
                <th class="text-center">Overtime</th>
            </tr>
        </thead>
        <tbody>
            @forelse($records as $index => $record)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $record->employee_name }}</td>
                    <td>{{ $record->department ?? 'N/A' }}</td>
                    <td>&#8369;{{ number_format($record->basic_salary, 2) }}</td>
                    <td class="text-red">&#8369;{{ number_format($record->deductions, 2) }}</td>
                    <td class="text-green">&#8369;{{ number_format($record->net_salary, 2) }}</td>
                    <td>{{ $record->absences ?? 0 }}</td>
                    <td>{{ $record->late_count ?? 0 }}</td>
                    <td>{{ $record->overtime_hours ?? 0 }} hrs</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align:center; padding:20px; color:#999;">
                        No payroll records found for {{ $month }}
                    </td>
                </tr>
            @endforelse
        </tbody>
        @if($records->count() > 0)
            <tfoot>
                <tr>
                    <td colspan="3">TOTAL</td>
                    <td>&#8369;{{ number_format($totalGross, 2) }}</td>
                    <td>&#8369;{{ number_format($totalDeductions, 2) }}</td>
                    <td>&#8369;{{ number_format($totalNet, 2) }}</td>
                    <td colspan="3"></td>
                </tr>
            </tfoot>
        @endif
    </table>

    <div class="footer">
        <p>Employee Management System &mdash; Payroll Report &mdash; {{ $month }} &mdash; {{ $generatedAt }}</p>
    </div>

</body>

</html>